### ISSUE TITLE
Bluetooth packages are being sent but nothing happens?

### ISSUE THREAD

**Issue by LumPao** [simondankelmann/Bluetooth-LE-Spam#241]
My two devices are the oneplus 8t and an oppo ax7, I started to spam on one of them and use spam detector on the other one and the packages do show up however the notification does not show up. I have switched the two around and the results are the same.

In summary nothing shows up but packages are being sent

**Comment by simondankelmann** [comment]
maybe the fastpairing feature is not enabled on your devices, otherwise please try placing both devices directly next to each other as the range is very low for that feature. if you see the packages in the detector the spam is executed successfully. but popups only appear if the proximity between sender and receiver is low.
