### ISSUE TITLE
Use advertising in settings

### ISSUE THREAD

**Issue by ChopPeep** [simondankelmann/Bluetooth-LE-Spam#76]
What does the use advertising in settings mean? Also, how can people help with adding more device codes?

**Comment by simondankelmann** [comment]
If this switch is enabled, it will trigger another method in the Android SDK to advertise the package. Instead of using "bluetoothLeAdvertiser.startAdvertisingSet," the method "bluetoothLeAdvertiser.startAdvertising" is employed. This method requires an instance of AdvertiseSettings as input instead of AdvertisingSetParameters. However, it appears that on certain devices, particularly Xiaomi devices, "bluetoothLeAdvertiser.startAdvertising" functions while "bluetoothLeAdvertiser.startAdvertisingSet" does not. If you do not see any success messages in the log output, please enable the switch and try the process again.

If you want to add some device codes please create a pull request  :)
